In [21]:
import networkx as nx
from itertools import permutations, combinations
import torch
import torch.nn as nn
import numpy as np


class SparseLinear(nn.Module):
    """Applies a linear transformation to the incoming data: :math:`y = xA^T + b`

    Args:
        in_features: size of each input sample
        out_features: size of each output sample
        connectivity: user defined sparsity matrix
        bias: If set to ``False``, the layer will not learn an additive bias.
            Default: ``True``
        coalesce_device: device to coalesce the sparse matrix on
            Default: 'gpu'
        max_size (int): maximum number of entries allowed before chunking occurrs
            Default: 1e8

    Shape:
        - Input: :math:`(N, *, H_{in})` where :math:`*` means any number of
          additional dimensions and :math:`H_{in} = \text{in\_features}`
        - Output: :math:`(N, *, H_{out})` where all but the last dimension
          are the same shape as the input and :math:`H_{out} = \text{out\_features}`.

    Attributes:
        weight: the learnable weights of the module of shape
            :math:`(\text{out\_features}, \text{in\_features})`. The values are
            initialized from :math:`\mathcal{U}(-\sqrt{k}, \sqrt{k})`, where
            :math:`k = \frac{1}{\text{in\_features}}`
        bias:   the learnable bias of the module of shape :math:`(\text{out\_features})`.
                If :attr:`bias` is ``True``, the values are initialized from
                :math:`\mathcal{U}(-\sqrt{k}, \sqrt{k})` where
                :math:`k = \frac{1}{\text{in\_features}}`

    Examples:

        >>> m = nn.SparseLinear(20, 30)
        >>> input = torch.randn(128, 20)
        >>> output = m(input)
        >>> print(output.size())
        torch.Size([128, 30])
    """

    def __init__(
        self,
        in_features,
        out_features,
        connectivity,
        bias=True,
        coalesce_device="cuda",
        max_size=1e8,
    ):
        assert in_features < 2**31 and out_features < 2**31
        if connectivity is not None:
            assert isinstance(connectivity, torch.LongTensor) or isinstance(
                connectivity,
                torch.cuda.LongTensor,
            ), "Connectivity must be a Long Tensor"
            assert (
                connectivity.shape[0] == 2 and connectivity.shape[1] > 0
            ), "Input shape for connectivity should be (2,nnz)"
            assert (
                connectivity.shape[1] <= in_features * out_features
            ), "Nnz can't be bigger than the weight matrix"
        super(SparseLinear, self).__init__()
        self.in_features = in_features
        self.out_features = out_features
        self.connectivity = connectivity
        self.max_size = max_size

        nnz = connectivity.shape[1]
        connectivity = connectivity.to(device=coalesce_device)
        indices = connectivity

        values = torch.empty(nnz, device=coalesce_device)

        self.register_buffer("indices", indices.cpu())
        self.weights = nn.Parameter(values.cpu())

        if bias:
            self.bias = nn.Parameter(torch.Tensor(out_features))
        else:
            self.register_parameter("bias", None)

        self.reset_parameters()

    def reset_parameters(self):
        bound = 1 / self.in_features**0.5
        nn.init.uniform_(self.weights, -bound, bound)
        if self.bias is not None:
            nn.init.uniform_(self.bias, -bound, bound)

    @property
    def weight(self):
        """returns a torch.sparse_coo_tensor view of the underlying weight matrix
        This is only for inspection purposes and should not be modified or used in any autograd operations
        """
        weight = torch.sparse_coo_tensor(
            self.indices,
            self.weights,
            (self.out_features, self.in_features),
        )
        return weight.coalesce().detach()

    def forward(self, inputs):
        output_shape = list(inputs.shape)
        output_shape[-1] = self.out_features

        if len(output_shape) == 1:
            inputs = inputs.view(1, -1)
        inputs = inputs.flatten(end_dim=-2)

        target = torch.sparse_coo_tensor(
            self.indices,
            self.weights,
            torch.Size([self.out_features, self.in_features]),
        )
        output = torch.sparse.mm(target, inputs.t()).t()

        if self.bias is not None:
            output += self.bias

        return output.view(output_shape)

    def extra_repr(self):
        return "in_features={}, out_features={}, bias={}, connectivity={}".format(
            self.in_features,
            self.out_features,
            self.bias is not None,
            self.connectivity,
        )


def separating_cliques(G):
    clique_1 = []
    clique_2 = []
    clique_3 = []
    clique_4 = []
    for clique in nx.enumerate_all_cliques(G):
        clique = set(clique)
        if len(clique) == 1:
            clique_1.append(clique)
        elif len(clique) == 2:
            clique_2.append(clique)
        elif len(clique) == 3:
            clique_3.append(clique)
        elif len(clique) == 4:
            clique_4.append(clique)
    return clique_1, clique_2, clique_3, clique_4


def get_connection(clique_last, clique_next):
    connection_list = [[], []]
    component_mapping = {i: x for i, x in enumerate(clique_last)}
    for i, clique in enumerate(clique_next):
        component = [set(x) for x in combinations(clique, len(clique) - 1)]
        index_next = i
        index_last = [
            list(component_mapping.keys())[list(component_mapping.values()).index(x)]
            for x in component
        ]
        for j in index_last:
            connection_list[0].append(j)
            connection_list[1].append(i)

    return connection_list


G = nx.Graph()
# Add 4 nodes
G.add_nodes_from([1, 2, 3, 4, 5])
# Add 4 edges
G.add_edges_from([(1, 2), (2, 3), (2, 4), (3, 4), (4, 5), (3, 5), (2, 5)])
G

In [ ]:
clique_1, clique_2, clique_3, clique_4 = separating_cliques(G)

connection_1 = get_connection(clique_1, clique_2)
connection_2 = get_connection(clique_2, clique_3)
connection_3 = get_connection(clique_3, clique_4)

connection_2

[[1, 2, 4, 1, 3, 5, 2, 3, 6, 4, 5, 6], [0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3]]

In [20]:
len_input = len(np.unique(connection_1[0]))
len_output = len(np.unique(connection_1[1]))

sl = SparseLinear(
    in_features=len_input,
    out_features=len_output,
    connectivity=torch.tensor([connection_1[1], connection_1[0]], dtype=torch.int64),
)
x = torch.ones(1, len_input)
output = sl(x)
print(output)

tensor([[ 0.6980, -0.3525, -0.5858, -0.2744, -0.2064,  0.2922, -0.3019]],
       grad_fn=<ViewBackward0>)


In [12]:
sl.weight.to_dense().numpy() @ x.numpy().T

array([[-0.06015173],
       [ 0.5625891 ],
       [-0.09905863],
       [ 0.12613186],
       [-0.22061317],
       [ 0.6008882 ],
       [ 0.        ]], dtype=float32)

In [13]:
sl.weight.to_dense().numpy()

array([[-0.06015173,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.06583074,  0.12741561,  0.1874524 ,  0.18189035,  0.        ],
       [ 0.        , -0.05709397,  0.        ,  0.        , -0.04196466],
       [-0.11316157,  0.        ,  0.30750433,  0.        , -0.06821091],
       [ 0.        , -0.01736058,  0.        , -0.20325258,  0.        ],
       [ 0.2300624 ,  0.3708258 ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ]],
      dtype=float32)

In [15]:
x

tensor([[1., 1., 1., 1., 1.]])

In [14]:
sl.weight

tensor(indices=tensor([[0, 1, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4],
                       [0, 0, 1, 2, 3, 1, 4, 5, 2, 4, 6, 3, 5, 6]]),
       values=tensor([-0.0602,  0.0658,  0.1274,  0.1875,  0.1819, -0.0571,
                      -0.0420, -0.1132,  0.3075, -0.0682, -0.0174, -0.2033,
                       0.2301,  0.3708]),
       size=(7, 5), nnz=14, layout=torch.sparse_coo)

In [5]:
num_batches = 3
x = torch.ones(3, len_input)
x[1, :] = 2
x[2, :] = 3

for i in range(len_input):
    x[:, i] = x[:, i] + i / 10

output = sl(x)
output

Shape of target: torch.Size([7, 5])
Shape of inputs.t(): torch.Size([5, 3])


RuntimeError: addmm: index out of column bound: 5 not between 1 and 5

In [26]:
import torch
import torch.nn as nn


class ConvFilter(nn.Module):
    def __init__(self, in_channels, out_channels):
        super().__init__()
        self.conv = nn.Conv2d(
            in_channels=in_channels,
            out_channels=out_channels,
            kernel_size=2,
            stride=2,
            padding=0,  # No padding for exact 2x downsampling
        )

    def forward(self, x):
        # x shape: (batch_size, channels, height, width)
        return self.conv(x)


# Example usage
batch_size = 4
in_channels = 1
out_channels = 8
rows = 100
cols = 6

# Create model
conv1_tetrahedra = nn.Sequential(
    nn.Conv2d(
        in_channels=in_channels,
        out_channels=8,
        kernel_size=(1, 2),
        stride=(1, 2),
    ),
    nn.ReLU(),
)
# Create batch of images
x = torch.randn(batch_size, in_channels, rows, cols)
print(f"Input shape: {x.shape}")  # torch.Size([4, 3, 32, 32])

# Apply convolution
output = conv1_tetrahedra(x)
print(f"Output shape: {output.shape}")  # torch.Size([4, 16, 16, 16])

Input shape: torch.Size([4, 1, 100, 6])
Output shape: torch.Size([4, 8, 100, 3])


In [30]:
import torch.nn.functional as F


class HNN(nn.Module):
    def __init__(
        self,
        num_nodes: int,
        num_edges: int,
        num_triangles: int,
        num_tetrahedra: int,
        nodes_to_edges_connections: tuple,
        edges_to_triangles_connections: tuple,
        triangles_to_tetrahedra_connections: tuple,
    ):
        """
        nodes_to_edges_connections: tuple of two lists, where the first list contains the indices of the edges
        and the second list contains the indices of the nodes connected to those edges, such that the i-th node
        in the first list is a member of the i-th edge in the second list.

        Same for edges_to_triangles_connections and triangles_to_tetrahedra_connections
        """
        super(HNN, self).__init__()
        self.sparse_layer_edges = SparseLinear(
            num_nodes,
            num_edges,
            connectivity=torch.tensor(
                [nodes_to_edges_connections[1], nodes_to_edges_connections[0]],
                dtype=torch.int64,
            ),
        )

        self.sparse_layer_triangles = SparseLinear(
            num_edges,
            num_triangles,
            connectivity=torch.tensor(
                [edges_to_triangles_connections[1], edges_to_triangles_connections[0]],
                dtype=torch.int64,
            ),
        )

        self.triangles_to_tetrahedra_connections = triangles_to_tetrahedra_connections

        if len(self.triangles_to_tetrahedra_connections[0]) != 0:
            self.sparse_layer_tetrahedra = SparseLinear(
                num_triangles,
                num_tetrahedra,
                connectivity=torch.tensor(
                    [
                        triangles_to_tetrahedra_connections[1],
                        triangles_to_tetrahedra_connections[0],
                    ],
                    dtype=torch.int64,
                ),
            )

        else:
            self.sparse_layer_tetrahedra = None

    def forward(self, x):
        x_s1 = F.relu(self.sparse_layer_edges(x))

        x_s2 = F.relu(self.sparse_layer_triangles(x_s1))

        if len(self.triangles_to_tetrahedra_connections[0]) != 0:
            x_s3 = F.relu(self.sparse_layer_tetrahedra(x_s2))

            return torch.cat([x_s1, x_s2, x_s3], 1)

        else:

            return torch.cat([x_s1, x_s2], 1)


hnn = HNN(
    num_nodes=len(clique_1),
    num_edges=len(clique_2),
    num_triangles=len(clique_3),
    num_tetrahedra=len(clique_4),
    nodes_to_edges_connections=connection_1,
    edges_to_triangles_connections=connection_2,
    triangles_to_tetrahedra_connections=connection_3,
)

x = torch.ones(1, len(clique_1))
output = hnn(x)
print(output)
print(output.shape)  # Should print the shape of the output tensor

tensor([[0.7730, 0.0756, 0.0871, 0.0632, 0.0000, 0.1362, 0.0000, 0.2796, 0.1956,
         0.0000, 0.2654, 0.0000]], grad_fn=<CatBackward0>)
torch.Size([1, 12])


In [47]:
len(clique_2), len(clique_3), len(clique_4)

(7, 4, 1)

In [48]:
max(connection_1[1]) + 1, max(connection_2[1]) + 1, max(connection_3[1]) + 1

(7, 4, 1)